telemetry:
  logs:
    level: DEBUG
    format: text
  metrics:
    enabled: true
    bindAddress: ":8080"
  health:
    enabled: true
    bindAddress: ":8181"
pfsense:
  url: http://localhost
  insecure: true
  username: admin
  password: admin
dryRun: true
